export const ROUTE_CHANGED = 'router/ROUTE_CHANGED';

export const SAVE_NEWESTVOTEHASH = 'SAVE_NEWESTVOTEHASH';
export const CLEAR_NEWESTVOTEHASH = 'CLEAR_NEWESTVOTEHASH';

export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

export const UPDATE_BALANCE = 'UPDATE_BALANCE';

export const UPDATE_VOTINGSTATUS = 'UPDATE_VOTINGSTATUS';

export const SET_ENDTIME = 'SET_ENDTIME';

export const SET_OWNER = 'SET_OWNER';

export const INCREMENT_VOTE = 'INCREMENT_VOTE';

export const INCREMENT_MYBIDS = 'INCREMENT_MYBIDS';
export const CLEAR_MYBIDS = 'CLEAR_MYBIDS';

export const UPDATE_TIME = 'UPDATE_TIME';

export const UPDATE_STARTSTATUS = 'UPDATE_STARTSTATUS';
export const CLEAR_STARTSTATUS = 'CLEAR_STARTSTATUS';
export const UPDATE_VOTESTATUS = 'UPDATE_VOTESTATUS';
export const CLEAR_VOTESTATUS = 'CLEAR_VOTESTATUS';
export const UPDATE_WITHDRAWSTATUS = 'UPDATE_WITHDRAWSTATUS';
export const CLEAR_WITHDRAWSTATUS = 'CLEAR_WITHDRAWSTATUS';

export const UPDATE_STARTDAYS = 'UPDATE_STARTDAYS';
export const UPDATE_STARTHOURS = 'UPDATE_STARTHOURS';
export const UPDATE_STARTMINUTES = 'UPDATE_STARTMINUTES';
export const UPDATE_STARTSECONDS = 'UPDATE_STARTSECONDS';

export const UPDATE_MOVIENAME = 'UPDATE_MOVIENAME';
export const CLEAR_MOVIENAME = 'CLEAR_MOVIENAME';
